### ISSUE TITLE
Unlocode validation

### ISSUE THREAD

**Issue by hazzyeer** [paoesco/cargotracker-ddd#1]
Is Unlocode validation exist just in the domain layer?
What about controllers and views?

**Comment by paoesco** [comment]
@hamzayoussef sorry for not coming back to you earlier.

Domain validation is enough here.
For instance, when calling changeDestination in https://github.com/paoesco/cargotracker-ddd/blob/develop/src/main/java/net/java/cargotracker/interfaces/booking/facade/internal/DefaultBookingServiceFacade.java , the domain will validate itself and will throw an error that can be caught by the application and interface layers.

Do you have another opinion on this ?
